# Generated by Django 4.2 on 2023-04-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("birthday", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "freelance",
                    models.CharField(
                        choices=[["True", "True"], ["False", "False"]],
                        default=True,
                        max_length=5,
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("education", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("details", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
