# Generated by Django 4.2 on 2023-04-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="skills_description",
            field=models.TextField(null=True),
        ),
    ]
