# Generated by Django 4.2 on 2023-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_project_projectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="detatils",
        ),
        migrations.AddField(
            model_name="project",
            name="details",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
