# Generated by Django 4.2 on 2023-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_contactmessage_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="read",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
