# Generated by Django 4.2 on 2023-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_contactmessage_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
